name: iris-sec CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yml
          auto-activate-base: false
          activate-environment: iris
          auto-update-conda: true
          
      - name: Set up Java 8/ Maven 3.5.0
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install java 8.0.452-amzn
          sdk install maven 3.5.0
          # Following make sure all envs persist across steps
          echo "JAVA_HOME=$(sdk home java)" >> $GITHUB_ENV
          echo "MAVEN_HOME=$(sdk home maven)" >> $GITHUB_ENV
          echo "$(sdk home java)/bin" >> $GITHUB_PATH
          echo "$(sdk home maven)/bin" >> $GITHUB_PATH
          echo "$HOME/.sdkman/bin" >> $GITHUB_PATH
        
      - name: Download CodeQL Bundle
        run: curl -L https://github.com/github/codeql-action/releases/download/codeql-bundle-v2.15.0/codeql-bundle-linux64.tar.gz -o codeql-bundle.tar.gz

      - name: Extract CodeQL Bundle
        run: tar -xzf codeql-bundle.tar.gz

      - name: Export to PATH
        run: |
          export PATH="$PWD/codeql:$PATH"
          echo "CODEQL_PATH=$(pwd)/codeql" >> $GITHUB_ENV
          echo "$(pwd)/codeql" >> $GITHUB_PATH

      - name: Update CodeQL Query version in config
        run: sed -i "s/^CODEQL_QUERY_VERSION = \".*\"$/CODEQL_QUERY_VERSION = \"0.8.0\"/" src/config.py

      - name: Build perwendel-spark
        run: |
          echo "JAVA_HOME is: $JAVA_HOME"
          echo "MAVEN_HOME is: $MAVEN_HOME"
          python scripts/setup.py --filter perwendel__spark_CVE-2018-9159_2.7.1

      - name: Generate CodeQL database
        run: python scripts/build_codeql_dbs.py --project perwendel__spark_CVE-2018-9159_2.7.1

      - name: Run IRIS
        run: python src/neusym_vul.py --query cwe-022wLLM --run-id test --llm qwen2.5-coder-7b perwendel__spark_CVE-2018-9159_2.7.1


        
