name: iris-sec CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: List contents of repository root
        run: ls -la

      - name: List contents of 'dockers' directory (if it exists)
        run: ls -la dockers/ || echo "dockers directory not found or empty"

      - name: Build Docker Image
        run: docker build -f dockers/Dockerfile --platform linux/amd64 -t iris:latest .

      - name: Run Analysis within Docker Container
        run: docker run --platform=linux/amd64 iris:latest /bin/bash -c
