name: iris-sec CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -f Dockerfile --platform linux/x86_64 -t iris:latest .

      - name: Run Analysis within Docker Container
        run: docker run --platform=linux/amd64 iris:latest
